{
# 公众号配置
# 公众号appId
"app_id": "wx83b6cb26c45a60fa",
# 公众号appSecret
"app_secret": "193d0ec583dc54a03b4c145ead92f266",
# 模板消息id
"template_id": "k_emO50irK6OyOmUAHYsUkJpUu_c6uvZZfp1gpS8i7M",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["oroi45reA9W12z7H7DveKPkexQso","oroi45iGIsUem9SWD4QLvO0aCOIk"],

# 信息配置
# 和风天气apikey
"weather_key": "7090a66364bd4301a64df4ccf05463f9",
# 天行数据apikey
"tian_api": "49fd356f6102b0500e5b40f2f512f849",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦(国外城市可能获取不到pm2.5，空气质量，今日建议等数据)
"region": "宣城市",
# 在一起的日子，格式同上
"love_date": "2021-09-24",
# 金句中文，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}
